github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

package:
  repositories:    ["docker.io/paketobuildpacks/eclipse-openj9", "gcr.io/paketo-buildpacks/eclipse-openj9"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "^8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jdk(.*8.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 8
  id:              jre
  version_pattern: "^8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jdk(.*8.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 11
  id:              jdk
  version_pattern: "^11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jdk(.*11.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 11
  id:              jre
  version_pattern: "^11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jdk(.*11.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 17
  id:              jdk
  version_pattern: "^17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jdk(.*17.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 17
  id:              jre
  version_pattern: "^17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jdk(.*17.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 21
  id:              jdk
  version_pattern: "^21(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru21-binaries
    tag_filter: jdk(.*21.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 21
  id:              jre
  version_pattern: "^21(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru21-binaries
    tag_filter: jdk(.*21.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
# ARM64
- name:            JDK 8 ARM64
  id:              jdk
  version_pattern: "^8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jdk(.*8.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JRE 8 ARM64
  id:              jre
  version_pattern: "^8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jdk(.*8.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JDK 11 ARM64
  id:              jdk
  version_pattern: "^11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:    "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jdk(.*11.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JRE 11 ARM64
  id:              jre
  version_pattern: "^11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jdk(.*11.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "^17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jdk(.*17.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JRE 17 ARM64
  id:              jre
  version_pattern: "^17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jdk(.*17.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "^21(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru21-binaries
    tag_filter: jdk(.*21.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64
- name:            JRE 21 ARM64
  id:              jre
  version_pattern: "^21(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  cpe_pattern:     "[\\d]+\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_aarch64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru21-binaries
    tag_filter: jdk(.*21.*)
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: arm64