github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/eclipse-openj9
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jdk(.*8.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JRE 8
  id:              jre
  version_pattern: "8(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru8-binaries
    tag_filter: jre(.*8.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JDK 11
  id:              jdk
  version_pattern: "11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jdk(.*11.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JRE 11
  id:              jre
  version_pattern: "11(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru11-binaries
    tag_filter: jre(.*11.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JDK 16
  id:              jdk
  version_pattern: "16(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru16-binaries
    tag_filter: jdk(.*16.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JRE 16
  id:              jre
  version_pattern: "16(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru16-binaries
    tag_filter: jre(.*16.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JDK 17
  id:              jdk
  version_pattern: "17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jdk_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jdk(.*17.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
- name:            JRE 17
  id:              jre
  version_pattern: "17(?:\\.[\\d]+(?:\\.[\\d]+)?)?"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/ibm-semeru-dependency:main
  with:
    glob: ibm-semeru-open-jre_x64_linux_.+_openj9-.+.tar.gz
    owner: ibmruntimes
    repository: semeru17-binaries
    tag_filter: jre(.*17.)
    token: ${{ secrets.JAVA_GITHUB_TOKEN }}
